version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/app"
    versioning-strategy: lockfile-only
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"